// User roles
export enum UserRole {
  ADMIN = 'ADMIN',
  EXPERT = 'EXPERT',
  MANAGER = 'MANAGER',
  OPERATOR = 'OPERATOR',
  VIEWER = 'VIEWER',
}

// User status
export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}

// User data interface
export interface User {
  id: string
  name: string
  email: string
  avatar: string
  role: UserRole
  status: UserStatus
  department: string
  location: string
  phone: string
  lastActive: string
}

// Mock user data
export const users: User[] = [
  {
    id: '1',
    name: 'Ahmet Yılmaz',
    email: 'ahmet.yilmaz@example.com',
    avatar: 'https://i.pravatar.cc/150?img=1',
    role: UserRole.ADMIN,
    status: UserStatus.ACTIVE,
    department: 'Yönetim',
    location: 'İstanbul',
    phone: '+90 555 123 4567',
    lastActive: '2 dakika önce',
  },
  {
    id: '2',
    name: 'Ayşe Demir',
    email: 'ayse.demir@example.com',
    avatar: 'https://i.pravatar.cc/150?img=2',
    role: UserRole.EXPERT,
    status: UserStatus.ACTIVE,
    department: 'Uzmanlık',
    location: 'Ankara',
    phone: '+90 555 234 5678',
    lastActive: '5 dakika önce',
  },
  {
    id: '3',
    name: 'Mehmet Kaya',
    email: 'mehmet.kaya@example.com',
    avatar: 'https://i.pravatar.cc/150?img=3',
    role: UserRole.MANAGER,
    status: UserStatus.ACTIVE,
    department: 'Yönetim',
    location: 'İzmir',
    phone: '+90 555 345 6789',
    lastActive: '10 dakika önce',
  },
  {
    id: '4',
    name: 'Fatma Şahin',
    email: 'fatma.sahin@example.com',
    avatar: 'https://i.pravatar.cc/150?img=4',
    role: UserRole.OPERATOR,
    status: UserStatus.INACTIVE,
    department: 'Operasyon',
    location: 'Bursa',
    phone: '+90 555 456 7890',
    lastActive: '1 saat önce',
  },
  {
    id: '5',
    name: 'Ali Öztürk',
    email: 'ali.ozturk@example.com',
    avatar: 'https://i.pravatar.cc/150?img=5',
    role: UserRole.VIEWER,
    status: UserStatus.PENDING,
    department: 'İzleme',
    location: 'Antalya',
    phone: '+90 555 567 8901',
    lastActive: '2 saat önce',
  },
  {
    id: '6',
    name: 'Zeynep Çelik',
    email: 'zeynep.celik@example.com',
    avatar: 'https://i.pravatar.cc/150?img=6',
    role: UserRole.EXPERT,
    status: UserStatus.ACTIVE,
    department: 'Uzmanlık',
    location: 'İstanbul',
    phone: '+90 555 678 9012',
    lastActive: '3 saat önce',
  },
  {
    id: '7',
    name: 'Mustafa Aydın',
    email: 'mustafa.aydin@example.com',
    avatar: 'https://i.pravatar.cc/150?img=7',
    role: UserRole.MANAGER,
    status: UserStatus.ACTIVE,
    department: 'Yönetim',
    location: 'Ankara',
    phone: '+90 555 789 0123',
    lastActive: '4 saat önce',
  },
  {
    id: '8',
    name: 'Selin Yıldız',
    email: 'selin.yildiz@example.com',
    avatar: 'https://i.pravatar.cc/150?img=8',
    role: UserRole.OPERATOR,
    status: UserStatus.INACTIVE,
    department: 'Operasyon',
    location: 'İzmir',
    phone: '+90 555 890 1234',
    lastActive: '5 saat önce',
  },
  {
    id: '9',
    name: 'Burak Arslan',
    email: 'burak.arslan@example.com',
    avatar: 'https://i.pravatar.cc/150?img=9',
    role: UserRole.VIEWER,
    status: UserStatus.ACTIVE,
    department: 'İzleme',
    location: 'Bursa',
    phone: '+90 555 901 2345',
    lastActive: '6 saat önce',
  },
  {
    id: '10',
    name: 'Deniz Korkmaz',
    email: 'deniz.korkmaz@example.com',
    avatar: 'https://i.pravatar.cc/150?img=10',
    role: UserRole.EXPERT,
    status: UserStatus.PENDING,
    department: 'Uzmanlık',
    location: 'Antalya',
    phone: '+90 555 012 3456',
    lastActive: '7 saat önce',
  },
  {
    id: '11',
    name: 'Elif Yalçın',
    email: 'elif.yalcin@example.com',
    avatar: 'https://i.pravatar.cc/150?img=11',
    role: UserRole.MANAGER,
    status: UserStatus.ACTIVE,
    department: 'Yönetim',
    location: 'İstanbul',
    phone: '+90 555 123 4567',
    lastActive: '8 saat önce',
  },
  {
    id: '12',
    name: 'Emre Koç',
    email: 'emre.koc@example.com',
    avatar: 'https://i.pravatar.cc/150?img=12',
    role: UserRole.OPERATOR,
    status: UserStatus.INACTIVE,
    department: 'Operasyon',
    location: 'Ankara',
    phone: '+90 555 234 5678',
    lastActive: '9 saat önce',
  },
  {
    id: '13',
    name: 'Gizem Özkan',
    email: 'gizem.ozkan@example.com',
    avatar: 'https://i.pravatar.cc/150?img=13',
    role: UserRole.VIEWER,
    status: UserStatus.ACTIVE,
    department: 'İzleme',
    location: 'İzmir',
    phone: '+90 555 345 6789',
    lastActive: '10 saat önce',
  },
  {
    id: '14',
    name: 'Hakan Doğan',
    email: 'hakan.dogan@example.com',
    avatar: 'https://i.pravatar.cc/150?img=14',
    role: UserRole.EXPERT,
    status: UserStatus.PENDING,
    department: 'Uzmanlık',
    location: 'Bursa',
    phone: '+90 555 456 7890',
    lastActive: '11 saat önce',
  },
  {
    id: '15',
    name: 'İrem Aktaş',
    email: 'irem.aktas@example.com',
    avatar: 'https://i.pravatar.cc/150?img=15',
    role: UserRole.MANAGER,
    status: UserStatus.ACTIVE,
    department: 'Yönetim',
    location: 'Antalya',
    phone: '+90 555 567 8901',
    lastActive: '12 saat önce',
  },
]
