/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateSubscribeCommand } from '../interfaces';
/**
 * SubscribesApi - axios parameter creator
 * @export
 */
export const SubscribesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateSubscribeCommand} createSubscribeCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSubscribe: async (createSubscribeCommand: CreateSubscribeCommand, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSubscribeCommand' is not null or undefined
            assertParamExists('addSubscribe', 'createSubscribeCommand', createSubscribeCommand)
            const localVarPath = `/api/Subscribes/add-subscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSubscribeCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubscribesApi - functional programming interface
 * @export
 */
export const SubscribesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubscribesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateSubscribeCommand} createSubscribeCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addSubscribe(createSubscribeCommand: CreateSubscribeCommand, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addSubscribe(createSubscribeCommand, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscribesApi.addSubscribe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubscribesApi - factory interface
 * @export
 */
export const SubscribesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubscribesApiFp(configuration)
    return {
        /**
         * 
         * @param {SubscribesApiAddSubscribeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addSubscribe(requestParameters: SubscribesApiAddSubscribeRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.addSubscribe(requestParameters.createSubscribeCommand, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addSubscribe operation in SubscribesApi.
 * @export
 * @interface SubscribesApiAddSubscribeRequest
 */
export interface SubscribesApiAddSubscribeRequest {
    /**
     * 
     * @type {CreateSubscribeCommand}
     * @memberof SubscribesApiAddSubscribe
     */
    readonly createSubscribeCommand: CreateSubscribeCommand
}

/**
 * SubscribesApi - object-oriented interface
 * @export
 * @class SubscribesApi
 * @extends {BaseAPI}
 */
export class SubscribesApi extends BaseAPI {
    /**
     * 
     * @param {SubscribesApiAddSubscribeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscribesApi
     */
    public addSubscribe(requestParameters: SubscribesApiAddSubscribeRequest, options?: RawAxiosRequestConfig) {
        return SubscribesApiFp(this.configuration).addSubscribe(requestParameters.createSubscribeCommand, options).then((request) => request(this.axios, this.basePath));
    }
}

