/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BodyPaintControlsEnum } from './body-paint-controls-enum';

/**
 * 
 * @export
 * @interface BodyPaintControlsReportCommand
 */
export interface BodyPaintControlsReportCommand {
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'hood'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'roof'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'trunk'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'rightFrontFender'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'leftFrontFender'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'rightFrontDoor'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'leftFrontDoor'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'rightRearDoor'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'leftRearDoor'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'rightRearFender'?: BodyPaintControlsEnum;
    /**
     * 
     * @type {BodyPaintControlsEnum}
     * @memberof BodyPaintControlsReportCommand
     */
    'leftRearFender'?: BodyPaintControlsEnum;
}



