/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BranchBaseCommand
 */
export interface BranchBaseCommand {
    /**
     * 
     * @type {string}
     * @memberof BranchBaseCommand
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchBaseCommand
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchBaseCommand
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchBaseCommand
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchBaseCommand
     */
    'identityNumber'?: string;
}

