/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BranchBaseCommand } from './branch-base-command';

/**
 * 
 * @export
 * @interface CreateCompanyCommand
 */
export interface CreateCompanyCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    'logoPath'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    'registrationNumber'?: string;
    /**
     * 
     * @type {Array<BranchBaseCommand>}
     * @memberof CreateCompanyCommand
     */
    'branches'?: Array<BranchBaseCommand>;
}

