/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TestPackageType } from './test-package-type';

/**
 * 
 * @export
 * @interface CreateTestPackageCommand
 */
export interface CreateTestPackageCommand {
    /**
     * 
     * @type {number}
     * @memberof CreateTestPackageCommand
     */
    'branchId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTestPackageCommand
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTestPackageCommand
     */
    'price'?: number;
    /**
     * 
     * @type {Array<TestPackageType>}
     * @memberof CreateTestPackageCommand
     */
    'vehicleCheckTypes'?: Array<TestPackageType>;
}

