/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateReportCommandBodyPaintControls } from './create-report-command-body-paint-controls';
// May contain unused imports in some cases
// @ts-ignore
import type { VehicleReportCommand } from './vehicle-report-command';

/**
 * 
 * @export
 * @interface CreateReportCommand
 */
export interface CreateReportCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateReportCommand
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReportCommand
     */
    'testPackageId'?: string;
    /**
     * 
     * @type {VehicleReportCommand}
     * @memberof CreateReportCommand
     */
    'vehicle'?: VehicleReportCommand;
    /**
     * 
     * @type {CreateReportCommandBodyPaintControls}
     * @memberof CreateReportCommand
     */
    'bodyPaintControls'?: CreateReportCommandBodyPaintControls | null;
    /**
     * 
     * @type {string}
     * @memberof CreateReportCommand
     */
    'testStartedDatetime'?: string;
}

