/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmployeeDto
 */
export interface EmployeeDto {
    /**
     * 
     * @type {number}
     * @memberof EmployeeDto
     */
    'branchId'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDto
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDto
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDto
     */
    'hireDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDto
     */
    'terminationDate'?: string | null;
}

