/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TestPackageDetailDto } from './test-package-detail-dto';

/**
 * 
 * @export
 * @interface TestPackageDto
 */
export interface TestPackageDto {
    /**
     * 
     * @type {string}
     * @memberof TestPackageDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestPackageDto
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof TestPackageDto
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof TestPackageDto
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestPackageDto
     */
    'endDate'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TestPackageDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TestPackageDto
     */
    'branchId'?: number;
    /**
     * 
     * @type {Array<TestPackageDetailDto>}
     * @memberof TestPackageDto
     */
    'tests'?: Array<TestPackageDetailDto>;
}

