/* tslint:disable */
/* eslint-disable */
/**
 * Rapor Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VehicleReportCommand
 */
export interface VehicleReportCommand {
    /**
     * 
     * @type {string}
     * @memberof VehicleReportCommand
     */
    'plateNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleReportCommand
     */
    'engineNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleReportCommand
     */
    'brand'?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleReportCommand
     */
    'model'?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleReportCommand
     */
    'chassisNumber'?: string;
    /**
     * 
     * @type {number}
     * @memberof VehicleReportCommand
     */
    'year'?: number;
    /**
     * 
     * @type {string}
     * @memberof VehicleReportCommand
     */
    'fuelType'?: string;
    /**
     * 
     * @type {number}
     * @memberof VehicleReportCommand
     */
    'kilometer'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof VehicleReportCommand
     */
    'originalLicense'?: boolean;
}

