// Araç Expert Uygulaması için Raporlar
export const reports = [
  {
    id: 1001,
    name: 'BMW 320i Motor Bakım Raporu',
    url: '/reports/1001',
    date: '22 Mart 2023',
    time: '14:30',
    location: 'İstanbul, Kadıköy',
    totalRevenue: '₺7.600,00',
    totalRevenueChange: '+%3,2',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.250',
    pageViewsChange: '+%5,2',
    status: 'Tamamlandı',
    imgUrl: '/reports/bmw-motor.jpg',
    thumbUrl: '/reports/bmw-motor-thumb.jpg',
  },
  {
    id: 1002,
    name: 'Mercedes C200 Fren Sistemi Kontrolü',
    url: '/reports/1002',
    date: '22 Mart 2023',
    time: '11:15',
    location: 'İstanbul, Beşiktaş',
    totalRevenue: '₺2.000,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '980',
    pageViewsChange: '+%2,1',
    status: 'Gecikmiş',
    imgUrl: '/reports/mercedes-fren.jpg',
    thumbUrl: '/reports/mercedes-fren-thumb.jpg',
  },
  {
    id: 1003,
    name: 'Audi A4 Şanzıman Tamiri',
    url: '/reports/1003',
    date: '21 Mart 2023',
    time: '16:45',
    location: 'İstanbul, Şişli',
    totalRevenue: '₺14.000,00',
    totalRevenueChange: '+%8,5',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '2.100',
    pageViewsChange: '+%7,3',
    status: 'Tamamlandı',
    imgUrl: '/reports/audi-sanziman.jpg',
    thumbUrl: '/reports/audi-sanziman-thumb.jpg',
  },
  {
    id: 1004,
    name: 'Volkswagen Golf Motor Arıza Tespiti',
    url: '/reports/1004',
    date: '20 Mart 2023',
    time: '10:30',
    location: 'İstanbul, Ataşehir',
    totalRevenue: '₺3.500,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.450',
    pageViewsChange: '+%3,8',
    status: 'Tamamlandı',
    imgUrl: '/reports/vw-golf.jpg',
    thumbUrl: '/reports/vw-golf-thumb.jpg',
  },
  {
    id: 1005,
    name: 'Toyota Corolla Periyodik Bakım',
    url: '/reports/1005',
    date: '19 Mart 2023',
    time: '13:20',
    location: 'İstanbul, Maltepe',
    totalRevenue: '₺1.800,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.120',
    pageViewsChange: '+%1,5',
    status: 'Tamamlandı',
    imgUrl: '/reports/toyota-corolla.jpg',
    thumbUrl: '/reports/toyota-corolla-thumb.jpg',
  },
  {
    id: 1006,
    name: 'Honda Civic Klima Bakımı',
    url: '/reports/1006',
    date: '18 Mart 2023',
    time: '15:10',
    location: 'İstanbul, Ümraniye',
    totalRevenue: '₺2.200,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '950',
    pageViewsChange: '+%2,2',
    status: 'Tamamlandı',
    imgUrl: '/reports/honda-civic.jpg',
    thumbUrl: '/reports/honda-civic-thumb.jpg',
  },
  {
    id: 1007,
    name: 'Ford Focus Şanzıman Yağı Değişimi',
    url: '/reports/1007',
    date: '17 Mart 2023',
    time: '09:45',
    location: 'İstanbul, Pendik',
    totalRevenue: '₺1.500,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '880',
    pageViewsChange: '+%1,8',
    status: 'Tamamlandı',
    imgUrl: '/reports/ford-focus.jpg',
    thumbUrl: '/reports/ford-focus-thumb.jpg',
  },
  {
    id: 1008,
    name: 'Renault Megane Fren Balatası Değişimi',
    url: '/reports/1008',
    date: '16 Mart 2023',
    time: '12:30',
    location: 'İstanbul, Kartal',
    totalRevenue: '₺2.800,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.050',
    pageViewsChange: '+%2,5',
    status: 'Tamamlandı',
    imgUrl: '/reports/renault-megane.jpg',
    thumbUrl: '/reports/renault-megane-thumb.jpg',
  },
  {
    id: 1009,
    name: 'Opel Astra Motor Arıza Tespiti',
    url: '/reports/1009',
    date: '15 Mart 2023',
    time: '14:15',
    location: 'İstanbul, Beylikdüzü',
    totalRevenue: '₺3.200,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.180',
    pageViewsChange: '+%3,1',
    status: 'Tamamlandı',
    imgUrl: '/reports/opel-astra.jpg',
    thumbUrl: '/reports/opel-astra-thumb.jpg',
  },
  {
    id: 1010,
    name: 'Fiat Egea Periyodik Bakım',
    url: '/reports/1010',
    date: '14 Mart 2023',
    time: '11:00',
    location: 'İstanbul, Bakırköy',
    totalRevenue: '₺1.900,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.050',
    pageViewsChange: '+%2,2',
    status: 'Tamamlandı',
    imgUrl: '/reports/fiat-egea.jpg',
    thumbUrl: '/reports/fiat-egea-thumb.jpg',
  },
  {
    id: 1011,
    name: 'Hyundai i20 Motor Bakımı',
    url: '/reports/1011',
    date: '13 Mart 2023',
    time: '16:30',
    location: 'İstanbul, Zeytinburnu',
    totalRevenue: '₺2.300,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.120',
    pageViewsChange: '+%2,8',
    status: 'Tamamlandı',
    imgUrl: '/reports/hyundai-i20.jpg',
    thumbUrl: '/reports/hyundai-i20-thumb.jpg',
  },
  {
    id: 1012,
    name: 'Kia Sportage Şanzıman Tamiri',
    url: '/reports/1012',
    date: '12 Mart 2023',
    time: '10:15',
    location: 'İstanbul, Sarıyer',
    totalRevenue: '₺12.500,00',
    totalRevenueChange: '+%5,2',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.850',
    pageViewsChange: '+%4,5',
    status: 'Tamamlandı',
    imgUrl: '/reports/kia-sportage.jpg',
    thumbUrl: '/reports/kia-sportage-thumb.jpg',
  },
  {
    id: 1013,
    name: 'Volvo XC60 Fren Sistemi Kontrolü',
    url: '/reports/1013',
    date: '11 Mart 2023',
    time: '13:45',
    location: 'İstanbul, Beyoğlu',
    totalRevenue: '₺3.800,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.320',
    pageViewsChange: '+%3,2',
    status: 'Tamamlandı',
    imgUrl: '/reports/volvo-xc60.jpg',
    thumbUrl: '/reports/volvo-xc60-thumb.jpg',
  },
  {
    id: 1014,
    name: 'Peugeot 3008 Motor Arıza Tespiti',
    url: '/reports/1014',
    date: '10 Mart 2023',
    time: '15:20',
    location: 'İstanbul, Esenyurt',
    totalRevenue: '₺4.200,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '1.450',
    pageViewsChange: '+%3,5',
    status: 'Tamamlandı',
    imgUrl: '/reports/peugeot-3008.jpg',
    thumbUrl: '/reports/peugeot-3008-thumb.jpg',
  },
  {
    id: 1015,
    name: 'Citroen C4 Klima Bakımı',
    url: '/reports/1015',
    date: '9 Mart 2023',
    time: '09:30',
    location: 'İstanbul, Gaziosmanpaşa',
    totalRevenue: '₺2.100,00',
    totalRevenueChange: '+%0',
    ticketsAvailable: 1,
    ticketsSold: 1,
    ticketsSoldChange: '+%100',
    pageViews: '980',
    pageViewsChange: '+%2,1',
    status: 'Tamamlandı',
    imgUrl: '/reports/citroen-c4.jpg',
    thumbUrl: '/reports/citroen-c4-thumb.jpg',
  },
]

// Rapor siparişleri
export const reportOrders = [
  {
    id: 3001,
    url: '/orders/3001',
    date: '22 Mart 2023',
    amount: {
      usd: '₺7.600,00',
      cad: '₺7.600,00',
      fee: '₺380,00',
      net: '₺7.220,00',
    },
    payment: {
      transactionId: 'ch_1KLf7AsYJ0Dda7fs3CC5d46TY',
      card: {
        number: '3897',
        type: 'Visa',
        expiry: '06 / 2024',
      },
    },
    customer: {
      name: 'Ahmet Yılmaz',
      email: 'ahmet.yilmaz@example.com',
      address: 'Kadıköy, İstanbul',
      country: 'Türkiye',
      countryFlagUrl: '/flags/tr.svg',
    },
    report: reports[0],
  },
  {
    id: 3002,
    url: '/orders/3002',
    date: '22 Mart 2023',
    amount: {
      usd: '₺2.000,00',
      cad: '₺2.000,00',
      fee: '₺100,00',
      net: '₺1.900,00',
    },
    payment: {
      transactionId: 'ch_2DLf5AsYJ0Ddb7fs3CC5d46TY',
      card: {
        number: '7421',
        type: 'Mastercard',
        expiry: '12 / 2026',
      },
    },
    customer: {
      name: 'Ayşe Kaya',
      email: 'ayse.kaya@example.com',
      address: 'Beşiktaş, İstanbul',
      country: 'Türkiye',
      countryFlagUrl: '/flags/tr.svg',
    },
    report: reports[1],
  },
  {
    id: 3003,
    url: '/orders/3003',
    date: '21 Mart 2023',
    amount: {
      usd: '₺14.000,00',
      cad: '₺14.000,00',
      fee: '₺700,00',
      net: '₺13.300,00',
    },
    payment: {
      transactionId: 'ch_3KLf6DfYJ0Db7fassCC546TY',
      card: {
        number: '5683',
        type: 'Visa',
        expiry: '06 / 2024',
      },
    },
    customer: {
      name: 'Ali Öztürk',
      email: 'ali.ozturk@example.com',
      address: 'Şişli, İstanbul',
      country: 'Türkiye',
      countryFlagUrl: '/flags/tr.svg',
    },
    report: reports[2],
  },
]
